name: myenv
channels:
  - pytorch
  - conda-forge
  - giuliorossetti
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - asn1crypto=1.3.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.8.2=py37_0
  - blas=1.0=mkl
  - bleach=3.1.4=py_0
  - ca-certificates=2021.10.26=h06a4308_2
  - cairo=1.14.12=h8948797_3
  - certifi=2021.10.8=py37h06a4308_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.6.0=py_0
  - cryptography=2.8=py37h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37h7b6447c_0
  - dask-core=2021.3.1=pyhd3eb1b0_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.10=h7b6447c_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - idna=2.9=py_1
  - imageio=2.9.0=py_0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.6.1=pyhd3eb1b0_0
  - jdcal=1.4.1=py_0
  - jedi=0.16.0=py37_1
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.0=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libllvm11=11.1.0=h3826bc1_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - nbconvert=5.6.1=py37_0
  - ncurses=6.2=he6710b0_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - nltk=3.4.5=py37_0
  - notebook=6.0.3=py37_0
  - olefile=0.46=py37_0
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1l=h7f8727e_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h049681c_0
  - parso=0.6.2=py_0
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pixman=0.40.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pygraphviz=1.3=py37h14c3975_1
  - pynndescent=0.5.5=pyh6c4a22f_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h8356626_5_cpython
  - python-dateutil=2.8.1=py_0
  - python-louvain=0.15=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37h7b6447c_2
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - scikit-image=0.17.2=py37hdf5156a_0
  - scikit-learn-extra=0.1.0b2=py37h03ebfcd_0
  - send2trash=1.5.0=py37_0
  - setuptools=46.1.3=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - soupsieve=2.0=py_0
  - sqlite=3.31.1=h7b6447c_0
  - statsmodels=0.12.0=py37h8f50634_0
  - tabulate=0.8.3=py37_0
  - tbb=2021.4.0=hd09550d_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tifffile=2020.10.1=py37hdd07704_2
  - tk=8.6.10=hed695b0_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchvision=0.5.0=py37_cu100
  - traitlets=4.3.3=py37_0
  - umap-learn=0.5.2=py37h89c1867_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wordcloud=1.8.1=py37h4abf009_0
  - xlrd=1.2.0=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.6.2
    - alembic==1.4.1
    - angel-cd==1.0.3
    - appdirs==1.4.4
    - astor==0.8.1
    - async-timeout==3.0.1
    - bimlpa==0.1.2
    - cachetools==4.2.1
    - celluloid==0.2.0
    - chinese-whispers==0.7.5
    - click==7.1.2
    - colorama==0.4.3
    - contextlib2==0.6.0.post1
    - coverage==6.1.1
    - cvxpy==1.1.18
    - cython==0.29.6
    - databricks-cli==0.16.2
    - demon==2.0.6
    - dm-sonnet==1.29
    - docker==5.0.3
    - dominate==2.6.0
    - dynetx==0.3.1
    - ecos==2.0.10
    - elasticdeform==0.4.9
    - eva-lcd==0.1.1
    - fast-pagerank==0.0.4
    - filelock==3.0.12
    - flask==2.0.2
    - future==0.18.2
    - gast==0.4.0
    - gensim==4.1.2
    - geomloss==0.2.4
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google==3.0.0
    - google-api-core==1.26.3
    - google-api-python-client==1.12.8
    - google-auth==1.28.0
    - google-auth-httplib2==0.1.0
    - google-images-search==1.3.8
    - googleapis-common-protos==1.53.0
    - gputil==1.4.0
    - graphriccicurvature==0.5.2.1
    - greenlet==1.1.2
    - grpcio==1.30.0
    - gunicorn==20.1.0
    - h5py==2.9.0
    - httplib2==0.19.1
    - igraph==0.9.8
    - importlib-metadata==1.7.0
    - infomap==1.9.0
    - itsdangerous==2.0.1
    - jinja2==3.0.3
    - jsonpatch==1.32
    - jsonpointer==2.1
    - kaggle==1.5.12
    - karateclub==1.2.2
    - keras==2.2.4
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - leidenalg==0.8.8
    - llvmlite==0.36.0
    - mako==1.1.6
    - markdown==3.3.4
    - markov-clustering==0.0.6.dev0
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - mlflow==1.22.0
    - mock==4.0.3
    - msgpack==1.0.0
    - multidict==4.7.6
    - nbformat==5.1.3
    - networkit==9.1.1
    - nf1==0.0.4
    - nose==1.3.7
    - numba==0.53.0
    - numpy==1.21.5
    - oauthlib==3.1.1
    - opencv-contrib-python-headless==4.2.0.34
    - osqp==0.6.2.post5
    - packaging==20.8
    - pandas==1.1.5
    - peakutils==1.3.3
    - pickle5==0.0.11
    - pillow==8.1.2
    - pip==21.0.1
    - plottify==1.0
    - pooch==1.5.2
    - pot==0.8.1.0
    - prometheus-flask-exporter==0.18.6
    - protobuf==3.12.2
    - pulp==2.6.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.9.0
    - pyclustering==0.10.1.2
    - pycombo==0.1.6
    - pyfiglet==0.8.post1
    - pygsp==0.5.1
    - pykeops==1.5
    - python-editor==1.0.4
    - python-igraph==0.9.8
    - python-levenshtein==0.12.2
    - python-resize-image==1.1.19
    - python-slugify==5.0.2
    - python-twitter==3.5
    - pyxlsb==1.0.6
    - pyyaml==5.3.1
    - qdldl==0.1.5.post0
    - querystring-parser==1.2.4
    - ray==0.8.6
    - redis==3.4.1
    - regex==2020.11.13
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacremoses==0.0.43
    - scienceplots==1.0.9
    - scikit-learn==1.0.2
    - scikit-multilearn==0.2.0
    - scikit-optimize==0.5.2
    - scipy==1.5.4
    - scs==3.0.1
    - seaborn==0.11.2
    - semantic-version==2.8.5
    - sklearn==0.0
    - smart-open==4.1.2
    - smmap==5.0.0
    - sqlalchemy==1.4.28
    - sqlparse==0.4.2
    - super-selfish==0.0.6
    - tensorboard==1.13.1
    - tensorboardx==2.1
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - tensorflow-probability==0.6.0
    - termcolor==1.1.0
    - text-unidecode==1.3
    - texttable==1.6.4
    - threadpoolctl==2.1.0
    - thresholdclustering==1.1
    - tokenizers==0.9.4
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - tornado==6.0.2
    - tqdm==4.62.3
    - transformers==4.1.1
    - tweepy==3.10.0
    - typing-extensions==4.0.1
    - uritemplate==3.0.1
    - visdom==0.1.8.9
    - websocket-client==0.58.0
    - werkzeug==2.0.1
    - wrapt==1.11.1
    - wurlitzer==3.0.2
    - yarl==1.4.2
    - youtube-dl==2020.12.14
    - youtube-search-python==1.3.2
